【Session2】天気予報を取得し、表示する
kou-yamamoto/yumemi-ios pull request #2
Opened 2021-04-25 08:56 UTC by kou-yamamoto

#### やったこと
- ボタンタップで天気予報を取得し、表示する機能を実装

2021-04-25 11:39 UTC, Sab-swiftlin reviewed
一点だけコメントしました。
他は問題ないですが、余裕があればサンプルのように表示する画像に色をつけられるとより良いですね。

2021-04-25 11:39 UTC, Sab-swiftlin commented on yumemi-ios/Resources/Assets.xcassets/cloudy.imageset/Contents.json
> +}
PDFをリソースとして追加する場合は以下を参考にシングルスケールにすると良いですね。
https://qiita.com/okamu_/items/085cfc5999db801020ff

2021-04-26 05:29 UTC, kou-yamamoto commented
@TomSuzuki106 みていただけるとありがたいです！！

2021-04-26 07:56 UTC, Sab-swiftlin requested changes
https://qiita.com/okamu_/items/085cfc5999db801020ff
こちらまだ実施されていないので画像がぼやけてしまっていますね。
このタイミングで対応しておいた方が良いかなと思います。

2021-04-26 11:00 UTC, merged